# Generated by Django 5.2.8 on 2026-04-08 14:49

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_institucional', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('matricula', models.CharField(max_length=10, unique=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.carrera')),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estatus')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facultad')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departamentos', to='core.facultad')),
            ],
        ),
        migrations.AddField(
            model_name='carrera',
            name='facultad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='core.facultad'),
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo_institucional', models.EmailField(max_length=100, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('codigo_empleado', models.CharField(max_length=10, unique=True)),
                ('disponibilidad', models.CharField(max_length=30)),
                ('disponibilidad_max', models.IntegerField(default=5)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.departamento')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.especialidad')),
                ('estatus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estatus')),
                ('facultad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.facultad')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('titulo', models.TextField()),
                ('periodo', models.CharField(max_length=10)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('calificacion', models.IntegerField(blank=True, null=True)),
                ('link_descarga_final', models.URLField(blank=True, max_length=500, null=True)),
                ('asesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tesis_asesoradas', to='core.profesor')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tesis_estados', to='core.estatus')),
                ('estudiantes', models.ManyToManyField(related_name='tesis', to='core.estudiante')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('contenido', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('hora', models.TimeField(auto_now_add=True)),
                ('estatus_comentario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estatus')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='core.tesis')),
            ],
        ),
        migrations.CreateModel(
            name='VersionTesis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='tesis/versiones/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])])),
                ('codigo_version', models.CharField(max_length=20)),
                ('nombre_entregable', models.CharField(max_length=255)),
                ('link_descarga', models.URLField(blank=True, max_length=500)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('estatus_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.estatus')),
                ('tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versiones', to='core.tesis')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
